charm-and-friends/charm-in-the-wild

README.md

This would be more on brand for charm. Unless there's a strong reason why we should follow the awesome list title, I vote we rename to charm in the wild

docs: rename to charm in the wild

---

README.md

Fix lint CI on the main branch

chore(README): convert heading to title case

---

README.md

Add Bubble Tea projects from https://github.com/charmbracelet/bubbletea/blob/master/README.md

 chore(README): add bubbeltea projects 

---

README.md

I built a project to play Conway's Game of Life in the terminal. This PR adds a link to it!

Add cli-of-life

---

README.md

This PR adds https://github.com/charm-community/tapioca, the first charm community project by @esdandreu

feat(README): add tapioca

---

README.md

Adds https://github.com/ramirezfernando/ube

feat(README): add ube

---

README.md

Hi, I was open a PR https://github.com/charmbracelet/bubbletea/pull/1113
I moved my changes here. 🍀

Add Skeleton in the wild

---

README.md

Follow up from https://github.com/charmbracelet/bubbletea/pull/1096 :)

docs(readme): add tetrigo

---

README.md

- **docs(featured): update in the wild with projects from Bubble Tea README**
- **docs: update name to charm and friends in footer**

docs: merge projects from bubble tea repo's in the wild section

---

README.md

chore(lint): fix ci

---

README.md

Adding a wordle game to this list

add wordle

---

README.md

I added my language acquisition TUI app LinGo to the list in the README.

Add LinGo to README

---

README.md

Vault is a terminal based chat application: https://github.com/athulreji/vault-client
I have used bubbletea for building the terminal UI for the chat application. This is my first Go project and i found bubbletea very easy to use. Thanks for developing such a good framework.

Add Vault to README

---

README.md

I built a little flappy bird clone!

README: Add flappy-gopher

---

README.md

The project works well and a demo is included in the project's README.

Add wordle-helper to featured list

---

README.md

https://codeberg.org/gregorni/gone-away
The project works as intended and a demo is present in its README.

README: Add gone-away

---

README.md

I made a TUI for system monitoring and was wondering if it can get added :)

README.md Added gobottom

---

README.md

This is a tool I built. I hope this makes  the cut :crossed_fingers: 
Thanks for the resource that is this repo, it's quite nice :)

Add termpicker to the list

---

README.md

Courtesy @Andrew-Wichmann.
Supersedes https://github.com/charmbracelet/bubbletea/pull/1402

chore(readme): add firework-cli

---

README.md

Adds reference to people who want to add their own components to the additional-bubbles

README.md: add ref to additional bubbles

---

README.md

See https://github.com/TerraConstructs/provider-explorer/blob/main/README.md for demo gif

Add provider-explorer

---

README.md

Adding BubbleCal, a terminal calendar application built with Bubble Tea and Lip Gloss.
- **Project**: [BubbleCal](https://github.com/yuvals1/bubblecal)
- **Description**: A fast, keyboard-driven terminal calendar with event management
- **Technologies**: Built with Bubble Tea and Lip Gloss
- **Category**: Productivity and Organization (added in alphabetical order)
- Month, Week, and Day views
- Event creation, editing, and deletion
- 6 built-in themes
- Vim-style keyboard navigation
- Persistent storage
Thanks for considering this addition to the Charm ecosystem showcase\!

Add BubbleCal to Productivity and Organization section

---

README.md

[SonicRadio](https://github.com/dancnb/sonicradio)
A stylish TUI radio player making use of [Radio Browser API](https://www.radio-browser.info/) and [Bubbletea](https://github.com/charmbracelet/bubbletea).

sonicradio

---

README.md

[NaSC](https://github.com/parnoldx/nascTUI) - is an TUI calculator where you do maths like a normal person.

Add NaSC to the index
